[package]
name = "PayDrops"
version = "1.0.0"
authors = []

[addresses]
fee_manager_address="0x1"
paydrop_addr="0x1"



[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
